name: eschool2021
channels:
  - default
  - conda-forge
dependencies:
  - anaconda-client
  - astropy
  - conda-build
  - cython
  - h5py
  - ipython
  - jupyter
  - jupyterlab
  - matplotlib
  - numba
  - numpy
  - pandas
  - pip
  - pyerfa
  - pytables
  - pytest
  - pytest-cov
  - python=3.9
  - pyyaml
  - scikit-hep>3.1,<3.3
  - scikit-learn
  - scipy
  - tqdm
  - twine
  - wheel
  - pip:
    - build
    - phasespace>1.0,<1.4
    - zfit>0.5,<0.7
