name: eschool2021
channels:
  - default
dependencies:
  - astropy
  - conda-build
  - cython
  - h5py
  - ipython
  - ipython
  - jupyter
  - jupyterlab
  - matplotlib
  - numba
  - numpy
  - pandas
  - pip
  - pytables
  - pytest
  - pytest-cov
  - python=3.9
  - pyyaml
  - scikit-learn
  - scipy
  - tqdm
  - twine
  - wheel
  - pip:
    - build
