name: eschool2021_shep
channels:
  - default
  - conda-forge
dependencies:
  - anaconda-client
  - astropy=4.2
  - conda-build
  - cython
  - h5py
  - ipython
  - jupyter
  - jupyterlab
  - matplotlib
  - seaborn
  - numba
  - numpy
  - pandas
  - pip
  - pyerfa=1.7.3
  - pytables
  - pytest
  - pytest-cov
  - python=3.9
  - pyyaml
  - scikit-hep>3.1,<3.3
  - scikit-learn
  - scipy
  - tqdm
  - twine
  - wheel
  # for zfit
  - iminuit
  - nlopt
  - numdifftools
  - tensorflow
  - tensorflow-probability
  - texttable
  - ordered-set
  - tabulate
  - uproot
  - dotmap
  - pip:
    - zfit>0.6,<0.8
    - phasespace>1.0,<1.4
    - build
