package:
  name: eschool21_cython_demo
  version: 0.1.0

source:
  path: ..

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  build:
    - {{ compiler("c") }}
  host:
    - python >=3.7
    - pip
    - setuptools
    - cython
    - numpy
  run:
    - python >=3.7
    - {{ pin_compatible('numpy') }}
test:
  imports:
    - eschool21_cython_demo.fibonacci
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/escape2020/school2021
  license: MIT
  license_family: MIT
  license_file: ../LICENSE
  description: Escape2020/school2021 packaging demo
  dev_url: https://github.com/escape2020/school2021
