name: github pages

on:
  pull_requests:
    branches:
      - main  # Set a branch to deploy

    jobs:
      build:
        runs-on: ubuntu-18.04
        steps:
          - uses: actions/checkout@v2
            with:
              submodules: true  # Fetch Hugo themes (true OR recursive)
              fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

          - name: Setup Hugo
            uses: peaceiris/actions-hugo@v2
            with:
              hugo-version: '0.81.0'
              # extended: true

          - name: Build
            run:
              cd docs; hugo --minify -d ../public;
              echo "$PWD";
              ls;

          - name: Test
            run: |
              bundle exec htmlproofer ./_site \
                --allow-hash-href \
                --check-html \
                --only-4xx \
                --disable-external \
                --empty-alt-ignore

  push:
    branches:
      - main

    jobs:
      deploy:
        runs-on: ubuntu-18.04
        steps:
        - name: Deploy
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./public
